### PR TITLE
Use GNU autotools for building

### PR DESCRIPTION
**Pull request by dryman**
The GNU autotools can generate `./configure` script that has standard options like so:

```
./configure --help
`configure' configures sse-popcount 0.1 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

To assign environment variables (e.g., CC, CFLAGS...), specify them as
VAR=VALUE.  See below for descriptions of some of the useful variables.

Defaults for the options are specified in brackets.

Configuration:
  -h, --help              display this help and exit
      --help=short        display options specific to this package
      --help=recursive    display the short help of all the included packages
  -V, --version           display version information and exit
...
Optional Features:
  --disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --enable-silent-rules   less verbose build output (undo: "make V=1")
  --disable-silent-rules  verbose build output (undo: "make V=0")
  --enable-dependency-tracking
                          do not reject slow dependency extractors
  --disable-dependency-tracking
                          speeds up one-time build
  --disable-ansi-console  disable support for ansi color seqences
```

This configure script can also detect host cpu features and export cpu flags: "g++-5 -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -mbmi2 -g -O2 -std=c++11" for whatever is supported on the host machine. 

The C preprocessor macro `HAVE_AVX2_INSTRUCTIONS` is also generated from configure script automatically, and will exports to `config.h`.

`Makefile` and `config.h` is removed as it is derived from the configure script.

The m4 autoconf macros are GPL licensed, but these build script would not violate this project's license. See http://www.gnu.org/licenses/exceptions.html

Let me know if there's any question.

### CODE REVIEW

**Comment by dryman** [comment]
The autoconf m4 macros are pulled from autoconf-archive
http://www.gnu.org/software/autoconf-archive/

**Comment by dryman** [comment]
Added `--with-ssse3` option that @jkflying originally added to the Makefile.
This option suppresses all the automatic cpu feature detection, and use only the -mssse3 -mpopcnt option for CXXFLAGS.

**Comment by WojciechMula** [comment]
Thank you for the contribution, it's cool. But I'm a bit afraid of making dependencies to another software (autotools, m4, and so on) in order to build two simple programs. :)

There is a more serious problem: the original Makefile builds deliberately three different versions of the programs. Thanks to that one can easily compare performance on different architectures. I don't know how to achieve this with configure. Also, the configure detects a compiler -- I work in an environment with different compilers (gcc, clang, sometimes intel's compiler) and I set up the compiler intentionally.

Could you please check if these things can be defined with configure?

**Comment by dryman** [comment]
Ah ok. I think I have to pull out the automatic architecture checks then. (It uses gcc only builtin).
The other options you specified can be made.

Compile with different compiler can be done by this:

```
CC=icc CXX=?? ./configure
make
```

The other possible environment variable you can change on build time are listed below

```
Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  LIBS        libraries to pass to the linker, e.g. -l<library>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CXX         C++ compiler command
  CXXFLAGS    C++ compiler flags
```

Building three programs instead of one I need to add some more code in.
I'll do that tomorrow as it kind of late now.

**Comment by WojciechMula** [comment]
If we're going to change the build system it would be perfect to keep it simple. Simple for both one-shot users and me. :) So:

./configure
make

should build **all** available targets (sse, avx, avx2) using the default compiler. And

./configure --with-clang
make avx2

should build just avx2 targets using clang.

It would be really great if targets names contain the architecture name and also the compiler name. It could be easily done with plain Makefiles, but how to do it in autotools?

**Comment by dryman** [comment]
Would this satisfy?
`CXX=<compiler to test> ./configure [--without-avx2]`
produces
`verify-[arch]-<compiler> and speed-[arch]-<compiler>`

I twitched it a bit so we can specify any kind of compiler, not hard coded it in configure option. I also made including avx2 turned on by default, which I believed most people having machine later than 2011 have the support. Let me know if this interface looks right to you.

```
CXX=gcc ./configure
make
# produces verify-gcc verify-avx-gcc verify-avx2-gcc and speed variants
CXX=gcc ./configure --without-avx2
# produces verify-gcc verify-avx-gcc
CXX=clang ./configure
# produces verify-clang verify-avx-clang verify-avx2-clang
```

**Comment by dryman** [comment]
Created another branch to include the compiler information. Closing this one.

**Pull request closed without merging**
