### PR TITLE
Add Harley-Seal popcount algorithm

### PR DESCRIPTION
**Pull request by kimwalisch**
Hi,

Please add the Harley-Seal popcount algorithm. To the best of my knowledge this is the fastest known algorithm which uses only integer instructions, hence it works on all CPUs. The algorithm is described in depth in the Hacker's Delight book (second edition) and you can probably also find the original paper on the web.

Here are the results on my Intel Core i7-6700 CPU @ 3.40GHz (Linux x86-64, GCC-5.2):

```
./speed_avx2 10000000 1000
LUT (uint8_t[256])            ... time = 2.711632 s
LUT (uint64_t[256])           ... time = 2.572202 s (speedup: 1.05)
bit parallel                  ... time = 2.591368 s (speedup: 1.05)
bit parallel optimized        ... time = 1.703079 s (speedup: 1.59)
harley-seal                   ... time = 0.790219 s (speedup: 3.43)
bit parallel optimized - SSE  ... time = 0.833144 s (speedup: 3.25)
SSSE3 [pshufb]                ... time = 0.543871 s (speedup: 4.99)
AVX2 [pshufb]                 ... time = 0.403595 s (speedup: 6.72)
CPU popcnt                    ... time = 0.466106 s (speedup: 5.82)
kim@kim-skylake:~/Desktop/sse-popcount$ ./verify_avx2 

test 'all zeros':
bit-parallel                  : OK
bit-parallel-optimized        : OK
harley-seal                   : OK
sse-bit-parallel              : OK
sse-lookup                    : OK
avx2-lookup                   : OK
cpu                           : OK

test 'all ones':
bit-parallel                  : OK
bit-parallel-optimized        : OK
harley-seal                   : OK
sse-bit-parallel              : OK
sse-lookup                    : OK
avx2-lookup                   : OK
cpu                           : OK

test 'asending':
bit-parallel                  : OK
bit-parallel-optimized        : OK
harley-seal                   : OK
sse-bit-parallel              : OK
sse-lookup                    : OK
avx2-lookup                   : OK
cpu                           : OK

test 'quasirandom':
bit-parallel                  : OK
bit-parallel-optimized        : OK
harley-seal                   : OK
sse-bit-parallel              : OK
sse-lookup                    : OK
avx2-lookup                   : OK
cpu                           : OK
```

P.S. you might want to change the algorithm description:

```
harley-seal             - Harley-Seal popcount (4th iteration)
```

to what ever you want.

### CODE REVIEW

**Comment by WojciechMula** [comment]
Great. thank you for the contribution.

**Comment by kimwalisch** [comment]
By the way:

No one has ever tried to convert the Harley-Seal popcount algorithm to use vector instructions. If the Harley-Seal popcount algorithm uses fewer instructions than any other know algorithm using only integer instructions then it is possible that an AVX or AVX2 Harley-Seal popcount implementation would also use fewer instructions than any other known AVX popcount algorithm.

The problem with all AVX/AVX2 popcounting algorithms in my opinion is memory bandwidth. Once you run any of these algorithms on memory which is not in the CPU's caches none of the AVX popcounting algorithms can beat a simple implementation which uses the POPCNT instruction by more than 10 percent (Intel Skylake i7-6700). And if you are using multi-threaded popcounting (like in my [primecount](https://github.com/kimwalisch/primecount) project) even AVX2 cannot beat POPCNT because of memory bandwidth limits.

Best regards,
Kim

**Comment by WojciechMula** [comment]
Indeed, it would be nice to develop a vector version of the algorithm.

And you're right about memory bandwidth. A solution for this problem could be software prefetching, I mean prefetch0, prefetch1 and so on.

**Comment by WojciechMula** [comment]
@kimwalisch I've just added SSE & AVX2 implementation of HS algorithm - and AVX2 is the fastest code, please take a look at https://github.com/WojciechMula/sse-popcount/issues/9#issuecomment-200960122.

BTW When AVX512 will appear, then carry-save adder can be expressed by just two instructions vpternlogd (http://0x80.pl/articles/avx512-ternary-functions.html).

**Pull request merged**
